"""Code generation for :mod:`autosartool`.

Generates ``ara::com`` C++ skeleton/proxy headers for each service interface,
an application ``main`` per executable, a per-machine Execution-Manifest JSON,
and a CMake build script. The generated code targets the Adaptive AUTOSAR
``ara::com`` API surface (skeleton/proxy, offer/find service, methods, events,
fields) so it compiles against a real AP stack with only include-path changes.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from .model import (
    AdaptiveApplication,
    PortDirection,
    PrimitiveType,
    Project,
    ServiceInterface,
)

_CPP_TYPE = {
    PrimitiveType.BOOLEAN.value: "bool",
    PrimitiveType.UINT8.value: "std::uint8_t",
    PrimitiveType.UINT16.value: "std::uint16_t",
    PrimitiveType.UINT32.value: "std::uint32_t",
    PrimitiveType.UINT64.value: "std::uint64_t",
    PrimitiveType.SINT8.value: "std::int8_t",
    PrimitiveType.SINT16.value: "std::int16_t",
    PrimitiveType.SINT32.value: "std::int32_t",
    PrimitiveType.SINT64.value: "std::int64_t",
    PrimitiveType.FLOAT32.value: "float",
    PrimitiveType.FLOAT64.value: "double",
    PrimitiveType.STRING.value: "ara::core::String",
}


def _cpp_type(type_name: str) -> str:
    return _CPP_TYPE.get(type_name, type_name)


def _header_guard(*parts: str) -> str:
    return "_".join(p.upper() for p in parts) + "_H_"


def _banner() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        "// ---------------------------------------------------------------------------\n"
        "// Generated by autosartool. Do not edit by hand.\n"
        f"// Generated: {ts}\n"
        "// ---------------------------------------------------------------------------\n"
    )


def generate(project: Project) -> dict[str, str]:
    """Return a mapping of relative file path -> file contents for *project*."""
    files: dict[str, str] = {}

    for si in project.service_interfaces:
        files[f"include/{project.package}/{si.name.lower()}_common.h"] = _gen_common_header(project, si)
        files[f"include/{project.package}/{si.name.lower()}_skeleton.h"] = _gen_skeleton_header(project, si)
        files[f"include/{project.package}/{si.name.lower()}_proxy.h"] = _gen_proxy_header(project, si)

    for ex in project.executables:
        app = project.find_application(ex.root_component)
        if app is not None:
            files[f"src/{ex.name.lower()}_main.cpp"] = _gen_app_main(project, ex, app)

    for machine in project.machines:
        manifest = _gen_execution_manifest(project, machine)
        files[f"etc/{machine.name.lower()}_execution_manifest.json"] = json.dumps(manifest, indent=2) + "\n"

    if project.service_instances:
        files["etc/service_instance_manifest.json"] = (
            json.dumps(_gen_service_instance_manifest(project), indent=2) + "\n"
        )

    files["CMakeLists.txt"] = _gen_cmake(project)
    return files


# --------------------------------------------------------------------------- #
# Service interface headers
# --------------------------------------------------------------------------- #
def _gen_common_header(project: Project, si: ServiceInterface) -> str:
    guard = _header_guard(project.package, si.name, "common")
    lines = [_banner(), f"#ifndef {guard}", f"#define {guard}", ""]
    lines += [
        "#include <cstdint>",
        "#include \"ara/com/types.h\"",
        "#include \"ara/core/string.h\"",
        "",
        f"namespace {project.package} {{",
        f"namespace {si.namespace} {{",
        "",
        f"// Service interface: {si.name}",
        f"class {si.name} {{",
        " public:",
        f"  static constexpr ara::com::ServiceIdentifierType kServiceIdentifier{{\"{si.name}\"}};",
        "",
    ]
    if si.methods:
        lines.append("  // --- Method output structs ---")
        for m in si.methods:
            outs = [a for a in m.arguments if a.direction.value in ("OUT", "INOUT")]
            if outs and not m.fire_and_forget:
                lines.append(f"  struct {m.name}Output {{")
                for a in outs:
                    lines.append(f"    {_cpp_type(a.type)} {a.name};")
                lines.append("  };")
        lines.append("")
    lines += ["};", "", f"}}  // namespace {si.namespace}", f"}}  // namespace {project.package}", "", f"#endif  // {guard}", ""]
    return "\n".join(lines)


def _gen_skeleton_header(project: Project, si: ServiceInterface) -> str:
    guard = _header_guard(project.package, si.name, "skeleton")
    lines = [_banner(), f"#ifndef {guard}", f"#define {guard}", ""]
    lines += [
        f"#include \"{project.package}/{si.name.lower()}_common.h\"",
        "#include \"ara/com/skeleton.h\"",
        "#include \"ara/core/future.h\"",
        "",
        f"namespace {project.package} {{",
        f"namespace {si.namespace} {{",
        "namespace skeleton {",
        "",
        f"// ara::com service skeleton for {si.name}. Application code derives from",
        "// this class and implements the pure-virtual service methods.",
        f"class {si.name}Skeleton : public ara::com::ServiceSkeleton {{",
        " public:",
        f"  using {si.name} = {project.package}::{si.namespace}::{si.name};",
        "",
        "  explicit {name}Skeleton(ara::com::InstanceIdentifier instance,".format(name=si.name),
        "                          ara::com::MethodCallProcessingMode mode =",
        "                              ara::com::MethodCallProcessingMode::kEvent);",
        "",
        "  void OfferService();",
        "  void StopOfferService();",
        "",
    ]
    for m in si.methods:
        ret = _method_return(si, m)
        params = _method_params(m)
        lines.append(f"  // Method '{m.name}' — implement in the derived class.")
        lines.append(f"  virtual {ret} {m.name}({params}) = 0;")
        lines.append("")
    for e in si.events:
        lines.append(f"  // Event '{e.name}' — call to publish a new sample.")
        lines.append(f"  void Send_{e.name}(const {_cpp_type(e.type)}& data);")
        lines.append("")
    for f in si.fields:
        if f.has_notifier:
            lines.append(f"  // Field '{f.name}' notifier.")
            lines.append(f"  void Update_{f.name}(const {_cpp_type(f.type)}& value);")
            lines.append("")
    lines += ["};", "", "}  // namespace skeleton", f"}}  // namespace {si.namespace}", f"}}  // namespace {project.package}", "", f"#endif  // {guard}", ""]
    return "\n".join(lines)


def _gen_proxy_header(project: Project, si: ServiceInterface) -> str:
    guard = _header_guard(project.package, si.name, "proxy")
    lines = [_banner(), f"#ifndef {guard}", f"#define {guard}", ""]
    lines += [
        f"#include \"{project.package}/{si.name.lower()}_common.h\"",
        "#include \"ara/com/proxy.h\"",
        "#include \"ara/core/future.h\"",
        "",
        f"namespace {project.package} {{",
        f"namespace {si.namespace} {{",
        "namespace proxy {",
        "",
        f"// ara::com service proxy for {si.name}. Clients use FindService() to",
        "// discover an instance and then invoke methods / subscribe to events.",
        f"class {si.name}Proxy : public ara::com::ServiceProxy {{",
        " public:",
        f"  using {si.name} = {project.package}::{si.namespace}::{si.name};",
        "",
        "  static ara::com::ServiceHandleContainer<ara::com::HandleType> FindService(",
        "      ara::com::InstanceIdentifier instance);",
        "",
        "  explicit {name}Proxy(const ara::com::HandleType& handle);".format(name=si.name),
        "",
    ]
    for m in si.methods:
        params = _method_params(m)
        if m.fire_and_forget:
            lines.append(f"  // Fire-and-forget method '{m.name}'.")
            lines.append(f"  void {m.name}({params});")
        else:
            ret = _method_return(si, m, proxy=True)
            lines.append(f"  // Method '{m.name}' — returns a future with the result.")
            lines.append(f"  {ret} {m.name}({params});")
        lines.append("")
    for e in si.events:
        lines.append(f"  // Event '{e.name}' subscription accessor.")
        lines.append(f"  ara::com::events::Event<{_cpp_type(e.type)}> {e.name};")
        lines.append("")
    for f in si.fields:
        lines.append(f"  // Field '{f.name}' accessor (getter/setter/notifier as configured).")
        lines.append(f"  ara::com::fields::Field<{_cpp_type(f.type)}> {f.name};")
        lines.append("")
    lines += ["};", "", "}  // namespace proxy", f"}}  // namespace {si.namespace}", f"}}  // namespace {project.package}", "", f"#endif  // {guard}", ""]
    return "\n".join(lines)


def _method_params(m) -> str:
    parts = []
    for a in m.arguments:
        if a.direction.value == "IN":
            parts.append(f"const {_cpp_type(a.type)}& {a.name}")
        elif a.direction.value == "INOUT":
            parts.append(f"{_cpp_type(a.type)}& {a.name}")
        # pure OUT args are returned via the Output struct / future
    return ", ".join(parts)


def _method_return(si: ServiceInterface, m, proxy: bool = False) -> str:
    outs = [a for a in m.arguments if a.direction.value in ("OUT", "INOUT")]
    if m.fire_and_forget:
        return "void"
    if outs:
        payload = f"{m.name}Output"
    else:
        payload = "void"
    if proxy:
        return f"ara::core::Future<{payload}>"
    return f"ara::core::Future<{payload}>"


# --------------------------------------------------------------------------- #
# Application main
# --------------------------------------------------------------------------- #
def _gen_app_main(project: Project, executable, app: AdaptiveApplication) -> str:
    lines = [_banner()]
    lines += [
        "#include <atomic>",
        "#include <csignal>",
        "#include <thread>",
        "",
        "#include \"ara/exec/execution_client.h\"",
        "#include \"ara/log/logging.h\"",
    ]
    for p in app.ports:
        si = project.find_service_interface(p.interface)
        if si is None:
            continue
        if p.direction == PortDirection.PROVIDED:
            lines.append(f"#include \"{project.package}/{p.interface.lower()}_skeleton.h\"")
        else:
            lines.append(f"#include \"{project.package}/{p.interface.lower()}_proxy.h\"")
    lines += [
        "",
        "namespace {",
        "std::atomic<bool> g_running{true};",
        "void SignalHandler(int) { g_running = false; }",
        "}  // namespace",
        "",
        "int main(int /*argc*/, char** /*argv*/) {",
        f"  ara::log::Logger& logger = ara::log::CreateLogger(\"{executable.name[:4].upper()}\", \"{executable.name}\");",
        f"  logger.LogInfo() << \"Starting {executable.name} (component {app.name})\";",
        "",
        "  std::signal(SIGTERM, SignalHandler);",
        "  std::signal(SIGINT, SignalHandler);",
        "",
        "  // Report running state to Execution Management.",
        "  ara::exec::ExecutionClient exec_client;",
        "  exec_client.ReportExecutionState(ara::exec::ExecutionState::kRunning);",
        "",
    ]
    for p in app.provided_ports():
        var = f"{p.name.lower()}_skeleton"
        lines.append(f"  // Provided port '{p.name}' offering interface {p.interface}.")
        lines.append(
            f"  // {project.package}::ara::skeleton::{p.interface}Skeleton {var}"
            f"(ara::com::InstanceIdentifier{{\"{p.name}\"}});"
        )
        lines.append(f"  // {var}.OfferService();")
        lines.append("")
    for p in app.required_ports():
        lines.append(f"  // Required port '{p.name}' discovering interface {p.interface}.")
        lines.append(
            f"  // auto handles = {project.package}::ara::proxy::{p.interface}Proxy::FindService("
            f"ara::com::InstanceIdentifier{{\"{p.name}\"}});"
        )
        lines.append("")
    lines += [
        "  while (g_running) {",
        "    std::this_thread::sleep_for(std::chrono::milliseconds(100));",
        "  }",
        "",
        f"  logger.LogInfo() << \"Shutting down {executable.name}\";",
        "  exec_client.ReportExecutionState(ara::exec::ExecutionState::kTerminating);",
        "  return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Manifests
# --------------------------------------------------------------------------- #
def _gen_execution_manifest(project: Project, machine) -> dict:
    processes = []
    for proc in project.processes:
        ex = project.find_executable(proc.executable)
        processes.append(
            {
                "process": proc.name,
                "executable": proc.executable,
                "version": ex.version if ex else "1.0.0",
                "schedulingPolicy": proc.scheduling_policy,
                "schedulingPriority": proc.priority,
                "coreAffinity": proc.core_affinity,
                "startupStates": proc.startup_states,
            }
        )
    return {
        "machine": machine.name,
        "autosarRelease": project.autosar_release,
        "machineStates": machine.machine_states,
        "functionalClusters": machine.functional_clusters,
        "processes": processes,
    }


def _gen_service_instance_manifest(project: Project) -> dict:
    instances = []
    for si in project.service_instances:
        entry = {
            "name": si.name,
            "serviceInterface": si.service_interface,
            "instanceId": si.instance_id,
            "binding": si.binding.value,
            "role": si.role.value,
        }
        if si.service_id is not None:
            entry["serviceId"] = si.service_id
        if si.udp_port is not None:
            entry["udpPort"] = si.udp_port
        if si.tcp_port is not None:
            entry["tcpPort"] = si.tcp_port
        instances.append(entry)
    return {"serviceInstances": instances}


# --------------------------------------------------------------------------- #
# CMake
# --------------------------------------------------------------------------- #
def _gen_cmake(project: Project) -> str:
    lines = [
        "# Generated by autosartool. Do not edit by hand.",
        "cmake_minimum_required(VERSION 3.16)",
        f"project({project.package} LANGUAGES CXX VERSION 1.0.0)",
        "",
        "set(CMAKE_CXX_STANDARD 14)",
        "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
        "",
        "# The Adaptive Platform stack (ara::com, ara::exec, ara::log) is expected to",
        "# be provided by find_package() from your AP vendor SDK.",
        "# find_package(ara-com REQUIRED)",
        "",
        "include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)",
        "",
    ]
    for ex in project.executables:
        src = f"src/{ex.name.lower()}_main.cpp"
        lines.append(f"add_executable({ex.name} {src})")
        lines.append(f"# target_link_libraries({ex.name} PRIVATE ara::com ara::exec ara::log)")
        lines.append(
            f"install(TARGETS {ex.name} RUNTIME DESTINATION opt/{ex.name.lower()}/bin)"
        )
        lines.append("")
    for machine in project.machines:
        manifest = f"etc/{machine.name.lower()}_execution_manifest.json"
        lines.append(
            f"install(FILES {manifest} DESTINATION opt/etc)"
        )
    if project.service_instances:
        lines.append("install(FILES etc/service_instance_manifest.json DESTINATION opt/etc)")
    lines.append("")
    return "\n".join(lines)
